version: "3"

services:
  frontend:
    build: ./frontend-example-docker
    ports:
      - 5000:5000
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  backend:
    build: ./backend-example-docker
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
      - REDIS_PORT=6379
